dir = ' -dir ../AutomationTesting/Tests/sale_reversal'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale_reversal_loop(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 500
                max2 = 898
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                random_num2 = "${Math.abs(99 + new Random().nextInt(max2+1))}"
                deviceID = ' -q 1234567890'
                trxID = ' -o 12345678901' + random_num2.toString()
                log = ' -lp saleLog' + i.toString() + '.LOG'
                data = ' -out saleData' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/sale0.txt ' + amount + dir + log + data + deviceID + trxID
                bat str 

                data = ' -in saleData' + i.toString()+ '.txt'  
                log = ' -lp reversalLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/reversal0.txt ' + data + dir + log + deviceID + trxID
                bat str
            }
        }
    }
}
/* def reversal(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                data = ' -in Data' + i.toString()+ '.txt'
                log = ' -lp reversalLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/reversal0.txt ' + data + dir + log
                bat str 
            }
        }
    }
} */

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
        stage('closeBatch1')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 1)
            }
        }

        stage('sale_reversal')
        {
            steps
            {
                sale_reversal_loop(120)
            }
            
        }
       /* stage('reversal')
        {
            steps
            {
                reversal(5)
            }
            
        } */
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
