
ip = ' -ip 192.168.1.2'
connType = '-t 0'

def preauth(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                dir = ' -dir ../AutomationTesting/Tests/preauths_then_completions'
                log = ' -lp Logs/preauthLog' + i.toString() + '.LOG'
                data = ' -out transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data
                bat str 
            }
        }
    }
}

def preauthComp(size)
{
    script
    {

        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                dir = ' -dir ../AutomationTesting/Tests/preauths_then_completions'
                log = ' -lp Logs/preauthCompletionLog' + i.toString() + '.LOG'
                data = ' -in transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + dir + log + data
                bat str
            }
        }
    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            dir = ' -dir ../AutomationTesting/Tests/preauths_then_completions'
            log = ' -lp Logs/closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath  +dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 1)
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth(3)
            }
            
        }

        stage('preauthCompletion')
        {
            steps
            {
                preauthComp(3)
            }
            
        }
        
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
