ip = ' -ip 192.168.1.2'
connType = '-t 0'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale()
{
        script
        {
            catchError(stageResult: 'FAILURE')
            {
                i = 0
                amount = '-a 5'
                dir = ' -dir ../AutomationTesting/Tests/sale_refund_higher_amount'
                log = ' -lp saleLog' + i.toString() + '.LOG'
                data = ' -out Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/sale0.txt ' + amount + data + dir + log
                bat str 
            }
        }
}

def refund()
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            i = 0
            amount = ' -a 20'
            dir = ' -dir ../AutomationTesting/Tests/sale_refund_higher_amount'
            log = ' -lp refundLog' + i.toString() + '.LOG'
            data = ' -in Data' + i.toString()+ '.txt'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/refund0.txt ' + data + amount + dir + log
            bat str
        }
    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            dir = ' -dir ../AutomationTesting/Tests/sale_refund_higher_amount'
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir  + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
            
        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 1)
            }
        }

        stage('sale')
        {
            steps
            {
                sale()
            }
            
        }

        stage('refund')
        {
            steps
            {
                refund()
            }
            
        }
        
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
