dir = ' -dir ../AutomationTesting/Tests/preauths_then_completions_then_refunds'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def preauth(size)
{
    script
    {
        for(int i= 0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 2
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                log = ' -lp preauthLog' + i.toString() + '.LOG'
                data = ' -out Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data
                bat str 
            }
        }
    }
}

def preauthComp(size)
{
    script
    {
        for(int i= 0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                log = ' -lp preauthCompletionLog' + i.toString() + '.LOG'
                data = ' -in Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + dir + log + data
                bat str
            }
        }
    }
}

def refund(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                data = '-in ../AutomationTesting/transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/refund0.txt ' + data
                bat str
            }
        }
    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {
        stage('Init')
        {
            steps
            {
                init() 
            }
        }

        stage('closeBatchStart')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 0)
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth(5)
            }
            
        }

        stage('preauthCompletion')
        {
            steps
            {
                preauthComp(5)
            }
            
        }

        stage('refund')
        {
            steps
            {
                refund(5)
            }
            
        }
        
        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }
    }
}
