dir = ' -dir ../AutomationTesting/Tests/sale_refund_lower_amount'

def init()
{
        script
        {
              bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale()
{
        script
        {
            catchError(stageResult: 'FAILURE')
            {
                i = 0
                amount = '-a 50'
                log = ' -lp preauthLog' + i.toString() + '.LOG'
                data = ' -out Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/sale0.txt ' + amount + data + dir + log
                bat str 
            }
        }
}

def refund()
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            i = 0
            amount = ' -a 20'
            log = ' -lp preauthCompLog' + i.toString() + '.LOG'
            data = ' -in Data' + i.toString()+ '.txt'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/refund0.txt ' + data + amount + dir + log
            bat str
        }
    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir  + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
            
        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 1)
            }
        }

        stage('sale')
        {
            steps
            {
                sale()
            }
            
        }

        stage('refund')
        {
            steps
            {
                refund()
            }
            
        }
        
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
