
ip = ' -ip 192.168.1.2'
connType = '-t 0'

def preauth(size, offset)
{
    script
    {
        for(int i= offset; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                data = ' -out ../AutomationTesting/transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + data
                bat str 
            }
        }
    }
}

def preauthComp(size, offset)
{
    script
    {
        for(int i= offset; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                data = '-in ../AutomationTesting/transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + data
                bat str
            }
        }
    }

}

def sale(size, offset)
{
    script
    {
        for(int i=offset; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                data = ' -out ../AutomationTesting/transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/sale0.txt ' + amount + data
                bat str 
            }
        }
    }
}

def refund(size, offset)
{
    script
    {
        for(int i=offset; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                data = ' -in ../AutomationTesting/transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/refund0.txt ' + data
                bat str 
            }
        }
    }
}

def closeBatch(valPath)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('closeBatchStart')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }

        stage('preauth1')
        {
            steps
            {
                preauth(4,0)
            }
            
        }
        
        stage('preauthCompletion1')
        {
            steps
            {
                preauthComp(4,0)
            }
        }

        stage('closeBatch1')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }

        stage('sale')
        {
            steps
            {
                sale(3,0)
            }
        }

        stage('refund')
        {
            steps
            {
                sale(2,0)
            }
        }

        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }
        stage('refund2')
        {
            steps
            {
                sale(3,2)
            }
        }
        
        stage('preauth3')
        {
            steps
            {
                preauth(3,0)
            }
            
        }

        stage('preauthCompletion2')
        {
            steps
            {
                preauth(1,0)
            }
            
        }

        stage('closeBatch3')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }

        stage('preauthCompletion4')
        {
            steps
            {
                preauth(3,1)
            }
            
        }
        
        stage('closeBatch4')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }
    }
}
