/*ip = ' -ip 192.168.0.103'
connType = ' -t 2'
globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
comPort = ' -serialPort COM6'
logsPort = ' -logsPort COM7'
baudRate = ' -baud 9600'
cur = ' -cur 975' */

dir = ' -dir ../AutomationTesting/Tests/t1_closeBatch'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' +' -vp ' + valPath + dir + log
            //str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log + comPort + baudRate + logsPort
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 0)
            }
        }
    }
}
