
ip = ' -ip 192.168.0.103'
connType = ' -t 2'
dir = ' -dir ../AutomationTesting/Tests/t3_Preauth_PreauthComp_wrongAuthCode'
globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
comPort = ' -serialPort COM6'
logsPort = ' -logsPort COM7'
baudRate = ' -baud 9600'
cur = ' -cur 975'


def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}


def preauth_preauthComp(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 9999
                random_q = "${Math.abs(1 + new Random().nextInt(max+1))}"
                q = ' -q ' + random_q.toString()
                max = 500
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                data = ' -out preauthData' + i.toString()+ '.txt'
                log = ' -lp preauthLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + data + dir + log + comPort + baudRate + cur + q + logsPort 
                bat str
                
                authCode = ' -auth 123456'     
                log = ' -lp preauthCompLog' + i.toString() + '.LOG'
                data = ' -in preauthData' + i.toString()+ '.txt'
                outData = ' -out CompData' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + data + dir + log + comPort + baudRate + cur + globalVal + logsPort + outData + authCode
                bat str 
            }
        }
    }
}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log + comPort + baudRate + logsPort
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
        stage('closeBatch1')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 1)
            }
        }
            
 
        stage('preauth_preauthComp')
        {
            steps
            {
                preauth_preauthComp(3)
            }
            
        }
        
   
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
