def preauth(iterations)
{
        script
        {
            for(int i=0;i<iterations; ++i)
            {
                catchError(stageResult: 'FAILURE')
                {
                    str = 'python.exe ../AutomationTesting/Main.py -t 0 -ip 192.168.1.2 -vp ../AutomationTesting/validation/preauth0.txt -a 35'
        
                    bat str 
                    
                    str = 'python.exe ../AutomationTesting/Main.py -t 0 -ip 192.168.1.2 -vp ../AutomationTesting/validation/preauthCompletion_wrong_input.txt -a 35 -in ../AutomationTesting/inData0.txt'
                    bat str
                }
            }
        }
}

def closeBatch(valFile)
{
    catchError(stageResult: 'FAILURE')
    {
        script
        {
            str = 'python.exe ../AutomationTesting/Main.py -t 0 -ip 192.168.1.2 -vp ' + valFile
            bat str
        }
    }
   
}

pipeline {
    agent any
  
    stages 
    {
        stage('closeBatchStart')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch1.txt')
            }
        }
        stage('preauth_preauthCompletion')
        {
            steps
            {
                preauth(2)
            }
            
        }
        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }
    }
}