dir = ' -dir ../AutomationTesting/Tests/201_sales'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale(size, offset)
{
    script
    {
        for(int i= offset; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 5
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                log = ' -lp saleLog' + i.toString() + '.LOG'
                data = ' -out Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/sale0.txt ' + amount + dir + log + data
                bat str 
            }
        }
    }
}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {
        stage('Init')
        {
            steps
            {
                init() 
            }
        }

       /* stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        } */

        stage('sale1')
        {
            steps
            {
                sale(151,0)
            }
            
        }
        /*
        stage('sale2')
        {
            steps
            {
                sale(200,100)
            }
            
        }
        stage('sale3')
        {
            steps
            {
                sale(201,200)
            }
            
        } */
  
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
