


def preauth(ip)
{
        script
        {
            catchError(stageResult: 'FAILURE')
            {
                i = 0
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                data = ' -out ../AutomationTesting/transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py -t 0 '+ ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + data
                bat str 
            }
        }
}

def preauthComp(ip)
{
    catchError(stageResult: 'FAILURE')
    {
        i = 0
        data = '-in ../AutomationTesting/transData/Data' + i.toString()+ '.txt'
        str = 'python.exe ../AutomationTesting/Main.py -t 0 '+ ip +' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + data
        bat str
    }
}

def closeBatch(ip, valPath)
{
    catchError(stageResult: 'FAILURE')
    {
        script
        {
            str = 'python.exe ../AutomationTesting/Main.py -t 0 '+ ip +' -vp ' + valPath
            bat str
        }
    }
   
}

pipeline {
    agent any

    stages 
    {
        def ip = '-ip 192.168.1.19'

        stage('closeBatchStart')
        {
            steps
            {
                        
                closeBatch(ip,'../AutomationTesting/validation/closeBatch1.txt')
            }
        }

        
        stage('preauthCompletion1')
        {
            steps
            {
                preauthComp(ip)
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth(ip)
            }
            
        }

        stage('preauthCompletion2')
        {
            steps
            {
                preauthComp(ip)
            }
            
        }
        
        stage('closeBatch')
        {
            steps
            {
                closeBatch(ip,'../AutomationTesting/validation/closeBatch.txt')
            }
        }
    }
}