dir = ' -dir ../AutomationTesting/Tests/completion_preauth'

def preauth()
{
        script
        {
            catchError(stageResult: 'FAILURE')
            {
                i = 0
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                log = ' -lp Logs/preauthLog' + i.toString() + '.LOG'
                data = ' -out transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data
                bat str 
            }
        }
}

def preauthComp(valPath)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            i = 0
            log = ' -lp Logs/preauthCompletionLog' + i.toString() + '.LOG'
            data = ' -in transData/Data' + i.toString()+ '.txt'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log + data
            bat str
        }
    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp Logs/closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 1)
            }
        }

        
        stage('preauthCompletion1')
        {
            steps
            {
                preauthComp('../AutomationTesting/validation/preauthCompletionError1.txt ')
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth()
            }
            
        }
            
        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
