
ip = ' -ip 192.168.1.2'
connType = '-t 0'

def preauth()
{
        script
        {
            catchError(stageResult: 'FAILURE')
            {
                i = 0
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                    
                data = ' -out transData/Data' + i.toString()+ '.txt'
                log = ' -lp Logs/preauthLog' + i.toString() + '.LOG'
                dir = ' -dir ../AutomationTesting/Tests/completion_preauth_completion'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data
                bat str 
            }
        }
}

def preauthComp(valPath)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            i = 0
            data = ' -in transData/Data' + i.toString()+ '.txt'
            log = ' -lp Logs/preauthCompletionLog' + i.toString() + '.LOG'
            dir = ' -dir ../AutomationTesting/Tests/completion_preauth_completion'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log + data
            bat str
        }
    }

}

def closeBatch(valPath)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp Logs/closeBatchLog' + i.toString() + '.LOG'
            dir = ' -dir ../AutomationTesting/Tests/completion_preauth_completion'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('closeBatchStart')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }

        
        stage('preauthCompletion1')
        {
            steps
            {
                preauthComp('../AutomationTesting/validation/preauthCompletionError1.txt ')
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth()
            }
            
        }

        stage('preauthCompletion2')
        {
            steps
            {
                preauthComp('../AutomationTesting/validation/preauthCompletion0.txt ')
            }
            
        }
        
        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }
    }
}
