dir = ' -dir ../AutomationTesting/Tests/completion_preauth_completion'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def preauth()
{
        script
        {
            catchError(stageResult: 'FAILURE')
            {
                i = 0
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                log = ' -lp preauthLog' + i.toString() + '.LOG'
                data = ' -out Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data
                bat str 
            }
        }
}

def preauthCompError(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            i = 0
            log = ' -lp preauthCompletionLog' + index.toString() + '.LOG'
            stan = ' -stan 0'
            authCode = ' -auth 000000'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp '  +valPath + dir + log + stan + authCode
            bat str
        }
    }

}

def preauthComp(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            i = 0
            log = ' -lp preauthCompletionLog' + index.toString() + '.LOG'
            data = ' -in Data' + i.toString()+ '.txt'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp '  +valPath + dir + log + data
            bat str
        }
    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {
        stage('Init')
        {
            steps
            {
                init() 
            }
        }

        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 1)
            }
        }

        
        stage('preauthCompletionError')
        {
            steps
            {
                preauthCompError('../AutomationTesting/validation/preauthCompletionError1.txt ', 1)
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth()
            }
            
        }
            
        stage('preauthCompletion2')
        {
            steps
            {
                preauthComp('../AutomationTesting/validation/preauthCompletion0.txt ', 2)
            }
        }
            
        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
