globalAmount = 0
refundsAmount = 0
dir = ' -dir ../AutomationTesting/Tests/sale_refund_batch_amount_check'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                amount = ' -a 10000'
                globalAmount += 10000   
                data = ' -out Data' + i.toString()+ '.txt'
                log = ' -lp saleLog' + i.toString() + '.LOG'
                globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/sale0.txt ' + amount + data + dir + log + globalVal
                bat str 
            }
        }
    }
}

def refund(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                amount = ' -a 5000'
                refundsAmount += 5000   
                data = ' -in Data' + i.toString()+ '.txt'
                log = ' -lp refundLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/refund0.txt ' + data + log + dir + amount
                bat str
            }
        }
    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            amount = ' -a ' + globalAmount.toString()
            reAmount = ' -rea ' + refundsAmount.toString()  
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log + amount + reAmount
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
            
        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 0)
            }
        }

        stage('sales')
        {
            steps
            {
                sale(2)
            }
            
        }
        stage('refunds')
        {
            steps
            {
                refund(1)
            }
            
        }
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }
    }
}
