dir = ' -dir ../AutomationTesting/Tests/sale_refund_batch_amount_check'
ip = ' -ip 192.168.0.103'
connType = '-t 2'
dir = ' -dir ../AutomationTesting/Tests/Sale_refund'
globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
comPort = ' -serialPort COM6'
logsPort = ' -logsPort COM7'
baudRate = ' -baud 9600'
cur = ' -cur 975'
globalAmount = 0
refundsAmount = 0


def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                amount = ' -a 100'
                globalAmount += 100
                data = ' -out saleData' + i.toString()+ '.txt'
                log = ' -lp saleLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip + ' -vp ../AutomationTesting/validation/sale0.txt ' + amount + data + dir + log + comPort + baudRate + cur + logsPort 
                bat str
            }
        }
    }
}

def refund(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                amount = ' -a 500'
                refundsAmount += 500
                log = ' -lp refundLog' + i.toString() + '.LOG'
                data = ' -in saleData' + i.toString()+ '.txt'
                outData = ' -out refundData' + i.toString()+ '.txt'    
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip + ' -vp ../AutomationTesting/validation/refund0.txt ' + amount + data + dir + log + comPort + baudRate + cur + logsPort + outData
                bat str 
              }
        }
    }
}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            amount = ' -a ' + globalAmount.toString()
            reAmount = ' -rea ' + refundsAmount.toString()
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log + comPort + baudRate + logsPort + amount + reAmount
            bat str
        }
    }
}


pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
            
        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 0)
            }
        }

        stage('sales')
        {
            steps
            {
                sale(2)
            }
            
        }
        stage('refunds')
        {
            steps
            {
                refund(1)
            }
            
        }
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }
    }
}
