
ip = ' -ip 192.168.1.2'
connType = '-t 0'
dir = ' -dir ../AutomationTesting/Tests/sale_void'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                data = ' -out Data' + i.toString()+ '.txt'
                log = ' -lp saleLog' + i.toString() + '.LOG'
                globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/sale0.txt ' + amount + data + dir + log + globalVal
                bat str 
            }
        }
    }
}
def cancelSale(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                data = ' -in Data' + i.toString()+ '.txt'
                log = ' -lp cancelSaleLog' + i.toString() + '.LOG'
                globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/cancelSale.txt ' + data + dir + log + globalVal
                bat str 
            }
        }
    }
}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
        stage('closeBatch1')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 1)
            }
        }

        stage('sale')
        {
            steps
            {
                sale(1)
            }
            
        }
        stage('cancelSale')
        {
            steps
            {
                cancelSale(1)
            }
            
        }
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
