/*PREAUTH COMPLETION REVERSAL STO COMPLETION */

dir = ' -dir ../AutomationTesting/Tests/preauths_then_refunds_then_completions'

def preauth(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()               
                data = ' -out Data' + i.toString()+ '.txt'
                log = ' -lp preauthLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + dir + ' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + data + log
                bat str 
 
            }
        }
    }
}

def preauthComp_reversal(size)
{
    script
    {
        for(int i= 0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                log = ' -lp preauthCompletionLog' + i.toString() + '.LOG'
                data = ' -in Data' + i.toString()+ '.txt'
                outData = ' -out preauthComplData' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + dir + log + data + outData + ' -vp ../AutomationTesting/validation/preauthCompletion0.txt '
                bat str

                data = ' -in preauthComplData' + i.toString()+ '.txt'
                log = ' -lp reversalLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/reversal0.txt ' + data + dir + log
                bat str
            }
        }
    }
}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {
        stage('closeBatch1')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth(50)
            } 
        }
        
        stage('preauthCompletion_reversal')
        {
            steps
            {
                preauthComp_reversal(50)
            }
            
        }
       stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
