ip = ' -ip 192.168.1.2'
connType = '-t 0'

def preauth()
{
        script
        {
            catchError(stageResult: 'FAILURE')
            {
                i = 0
                amount = '-a 5'
                data = ' -out ../AutomationTesting/OutData.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + data
                bat str 
            }
        }
}

def preauthComp()
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            i = 0
            data = ' -in ../AutomationTesting/OutData.txt'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + data
            bat str
        }
    }

}

def closeBatch(valPath)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('closeBatchStart')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt')
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth()
            }
            
        }

        stage('preauthCompletion')
        {
            steps
            {
                preauthComp()
            }
            
        }
        
        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }
    }
}
