dir = ' -dir ../AutomationTesting/Tests/preauth_2completions'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def preauth(size)
{
    script
    {
        for(int i= 0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                data = ' -out preauthData' + i.toString()+ '.txt'
                log = ' -lp preauthLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + dir +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + data + log
                bat str 
            }
        }
    }
}

def preauthComp(valPath, size)
{
    script
    {
        for(int i= 0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                log = ' -lp preauthCompletionLog' + i.toString() + '.LOG'
                data = ' -in preauthData' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + dir + log + data + ' -vp ../AutomationTesting/validation/preauthCompletion0.txt '
                bat str
            }
        }
    }
}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' +' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {
        stage('Init')
        {
            steps
            {
                init() 
            }
        }

        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth(8)
            }
        }
        
        stage('preauthCompletion1')
        {
            steps
            {
                preauthComp( '../AutomationTesting/validation/preauthCompletion0.txt ', 8)
            }
        }

        stage('preauthCompletion2')
        {
            steps
            {
                preauthComp('../AutomationTesting/validation/preauthCompletion0.txt ', 8)
            }
            
        }
        
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
