dir = ' -dir ../AutomationTesting/Tests/preauths_2completions'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def preauth()
{
        script
        {
            catchError(stageResult: 'FAILURE')
            {
                i = 0
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                log = ' -lp preauthLog' + i.toString() + '.LOG'
                data = ' -out Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data
                bat str 
            }
        }
}

def preauthComp(valPath)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            i = 0
            log = ' -lp preauthCompLog' + i.toString() + '.LOG'
            data = ' -in Data' + i.toString()+ '.txt'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log + data
            bat str
        }
    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {
        stage('Init')
        {
            steps
            {
                init() 
            }
        }

        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth()
            }
            
        }

        
        
        stage('preauthCompletion1')
        {
            steps
            {
                preauthComp( '../AutomationTesting/validation/preauthCompletion0.txt ')
            }
        }

        stage('preauthCompletion2')
        {
            steps
            {
                preauthComp('../AutomationTesting/validation/preauthCompletion0.txt ')
            }
            
        }
        
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
