
ip = ' -ip 192.168.1.2'
connType = '-t 0'
globalAmount = 0
dir = ' -dir ../AutomationTesting/Tests/sale_batch_amount_check'
def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 1000
                random_amount = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = ' -a ' + random_amount.toString()
                globalAmount += random_amount   
                data = ' -out Data' + i.toString()+ '.txt'
                log = ' -lp saleLog' + i.toString() + '.LOG'
                globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/sale0.txt ' + amount + data + dir + log + globalVal
                bat str 
            }
        }
    }
}


def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            amount = ' -a ' + globalAmount.toString()
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log + amount
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
            
        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 0)
            }
        }

        stage('sales')
        {
            steps
            {
                sale(5)
            }
            
        }

        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }
    }
}
