dir = ' -dir ../AutomationTesting/Tests/t1_journal'
ip = ' -ip 192.168.0.103'
connType = ' -t 2'
globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
comPort = ' -serialPort COM6'
logsPort = ' -logsPort COM7'
baudRate = ' -baud 9600'
cur = ' -cur 975'


def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def journal()
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            i = 0
            log = ' -lp journalLog' + i.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip + ' -vp ../AutomationTesting/validation/journal.txt ' + dir + log + comPort + baudRate + globalVal + logsPort
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
        
       stage('journal')
        {
            steps
            {
                journal()
            }
            
        }
    }
}
