ip = ' -ip 192.168.0.103'
connType = '-t 2'
dir = ' -dir ../AutomationTesting/Tests/status'
globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
comPort = ' -serialPort COM6'
logsPort = ' -logsPort COM7'
baudRate = ' -baud 9600'
cur = ' -cur 975'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}


def status()
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            
            log = ' -lp statusLog.LOG'
             str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/status.txt ' + data + dir + log + comPort + baudRate + cur + q + logsPort 
            bat str
        }
    }
}

pipeline {
    agent any
    
    stages 
    {
        stage('init')
        {
            steps
            {
                        
                init()
            }
        }
        stage('status')
        {
            steps
            {
                        
                status()
            }
        }
    }
}
