
ip = ' -ip 192.168.1.2'
connType = ' -t 0'

def status()
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            str = 'python.exe ../AutomationTesting/Main.py -vp ../AutomationTesting/validation/status.txt' + '-dir Tests/Status -lv Logs/log0.LOG' + ip + connType
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('status1')
        {
            steps
            {
                        
                status()
            }
        }

        stage('status2')
        {
            steps
            {
                status()
            }
        }
        
        stage('status3')
        {
            steps
            {
                status()
            }
        }
    }
}
