def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}


def hanshake()
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            dir = ' -dir ../AutomationTesting/Tests/hanshake'
            log = ' -lp handshakeLog.LOG'
            str = 'python.exe ../AutomationTesting/Main.py -vp ../AutomationTesting/validation/handshake.txt' + dir + log
            bat str
        }
    }
}

pipeline {
    agent any
    
    stages 
    {
        stage('init')
        {
            steps
            {
                        
                init()
            }
        }
        stage('hanshake')
        {
            steps
            {
                        
                hanshake()
            }
        }
    }
}
