
ip = ' -ip 192.168.1.2'
connType = ' -t 0'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}


def hanshake()
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            dir = ' -dir ../AutomationTesting/Tests/hanshake'
            log = ' -lp statusLog' + i.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py -vp ../AutomationTesting/validation/hanshake.txt' + ip + connType + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {
        stage('hanshake')
        {
            steps
            {
                        
                hanshake()
            }
        }
}
