dir = ' -dir ../AutomationTesting/Tests/Preauth_PreauthComp_wrongAmount'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}
def preauth()
{
        script
        {
            catchError(stageResult: 'FAILURE')
            {
                i = 0
                amount = ' -a 20'
                data = ' -out Data' + i.toString()+ '.txt'
                log = ' -lp preauthLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data
                bat str 
            }
        }
}

def preauthComp()
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            i = 0
            data = ' -in Data' + i.toString()+ '.txt'
            log = ' -lp preauthCompLog' + i.toString() + '.LOG'
            amount = ' -a 10'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/preauthCompletion_wrong_input.txt ' + ' -gv ../AutomationTesting/validation/globalValidations.txt ' + dir + log + data  + amount
            bat str
        }
    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
        stage('closeBatch1')
        {
            steps
            {
                       
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth()
            }
            
        }

        stage('preauthCompletion')
        {
            steps
            {
                preauthComp()
            }
            
        }
        
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
