dir = ' -dir ../AutomationTesting/Tests/Preauth_PreauthComp_batch_amount_check'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def preauth_preauthComp(size)
{
        script
        {
                for(int i=0; i< size; ++i)
                {
                        catchError(stageResult: 'FAILURE')
                        {
                           globalAmount += 1
                           amount = ' -a 1'

                            log = ' -lp preauthLog' + i.toString() + '.LOG'
                            data = ' -out Data' + i.toString()+ '.txt'
                            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data
                            bat str 

                            globalAmount += 1
                            log = ' -lp preauthCompletionLog' + i.toString() + '.LOG'
                            data = ' -in Data' + i.toString()+ '.txt'
                            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + dir + log + data
                            bat str
                        }
                }
                
        
            
        }
}


def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            amount = ' -a ' + globalAmount.toString()
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log + amount
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
            
        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 0)
            }
        }

        stage('preauths/preauthCompletions')
        {
            steps
            {
                preauth_preauthComp(2)
            }
            
        }

        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }
    }
}
