
ip = ' -ip 192.168.1.2'
connType = '-t 0'
globalAmount = 0
dir = ' -dir ../AutomationTesting/Tests/Preauth_PreauthComp_batch_amount_check'
def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def preauth_preauthComp(size)
{
        script
        {

                catchError(stageResult: 'FAILURE')
                {
                    i = 0
                    amount = ' -a 1000' 
                    globalAmount += 1000 
                    log = ' -lp preauthLog' + i.toString() + '.LOG'
                    data = ' -out Data' + i.toString()+ '.txt'
                    globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
                        
                    str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data + globalVal
                    bat str 

                    globalAmount += 1000
                    log = ' -lp preauthCompletionLog' + i.toString() + '.LOG'
                    data = ' -in Data' + i.toString()+ '.txt'
                    str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + dir + log + data + globalVal
                    bat str
                }
        
            
        }
}


def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            amount = ' -a ' + globalAmount.toString()
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log + amount
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
            
        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 0)
            }
        }

        stage('preauths/preauthCompletions')
        {
            steps
            {
                preauth_preauthComp(1)
            }
            
        }

        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }
    }
}
