ip = ' -ip 192.168.0.103'
connType = ' -t 2'
dir = ' -dir ../AutomationTesting/Tests/t1_preauths'
globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
comPort = ' -serialPort COM6'
logsPort = ' -logsPort COM7'
baudRate = ' -baud 9600'
cur = ' -cur 975'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def preauthComp(size)
{
    script
    {
        for(int i= 0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                log = ' -lp preauthCompletionLog' + i.toString() + '.LOG'
                data = ' -in preauthData' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + globalVal + connType + ip + dir + comPort + logsPort + baudRate + cur + log + data + ' -vp ../AutomationTesting/validation/preauthCompletion0.txt '
                bat str
            }
        }
    }

}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
        
        stage('preauthCompletion')
        {
            steps
            {
                preauthComp(1)
            }
        }
    }
}
