dir = ' -dir ../AutomationTesting/Tests/sales_authCode_RRN'

def sale(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                data = ' -out transData/Data' + i.toString()+ '.txt'
                log = ' -lp Logs/saleLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/sale0.txt ' + amount + dir + log + data
                bat str 
            }
        }
    }
}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp Logs/closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath  + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 1)
            }
        }

        stage('sale')
        {
            steps
            {
                sale(3)
            }
            
        }

        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
