
ip = ' -ip 192.168.1.19'
connType = '-t 0'

def preauth(size)
{
        script
        {
            for(int i=0; i<size; ++i)
            {
                catchError(stageResult: 'FAILURE')
                {
                    max = 98
                    random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                    amount = '-a' + random_num.toString()
                    data = ' -out ../AutomationTesting/transData/Data' + i.toString()+ '.txt'
                    str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + data
                    bat str 
                }
            }
        }
}

def closeBatch(valPath)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('closeBatchStart')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt')
            }
        }

        stage('preauths')
        {
            steps
            {
                preauth()
            }
            
        }

        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }
    }
}