dir = ' -dir ../AutomationTesting/Tests/diagnostics'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}


def diagnostics()
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp diagnosticsLog.LOG'
            str = 'python.exe ../AutomationTesting/Main.py -vp ../AutomationTesting/validation/diagnostics.txt' + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {
        stage('init')
        {
            steps
            {
                        
                init()
            }
        }
        stage('diagnostics')
        {
            steps
            {
                        
                diagnostics()
            }
        }
    }
}
