ip = ' -ip 192.168.0.103'
connType = ' -t 2'
dir = ' -dir ../AutomationTesting/Tests/t2_completion_preauth'
globalVal = ' -gv ../AutomationTesting/validation/globalValidations.txt'
comPort = ' -serialPort COM6'
logsPort = ' -logsPort COM7'
baudRate = ' -baud 9600'
cur = ' -cur 975'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def preauth(size)
{
    script
    {
        for(int i= 0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()              
                data = ' -out preauthData' + i.toString()+ '.txt'
                log = ' -lp preauthLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip + dir + comPort + logsPort + baudRate + cur +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + data + log
                bat str 
            }
        }
    }
}

def preauthComp(size)
{
    script
    {
        for(int i= 0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                amount = ' -a 10'
                stan = ' -stan 0000'
                authCode = ' -auth 000000'
                log = ' -lp preauthCompletionLog' + i.toString() + '.LOG'
                data = ' -in preauthData' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + authCode + stan + amount + connType + ip + dir + comPort + logsPort + baudRate + cur + log + ' -vp ../AutomationTesting/validation/preauthCompletionError1.txt ' + data
                bat str
            }
        }
    }

}

pipeline {
    agent any

    stages 
    {
            stage("init")
            {
                    steps
                    {
                            init()
                    }
            }
        stage('preauthCompletion1')
        {
            steps
            {
                preauthComp(5)
            }
        }

        stage('preauth')
        {
            steps
            {
                preauth(5)
            }
            
        }
    }
}
