
ip = ' -ip 192.168.1.2'
connType = '-t 0'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                data = ' -out Data' + i.toString()+ '.txt'
                log = ' -lp saleLog' + i.toString() + '.LOG'
                dir = ' -dir ../AutomationTesting/Tests/Sale_refund_wrong_input'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/sale0.txt ' + amount + data + dir + log
                bat str 
            }
        }
    }
}

def refund(size)
{
    script
    {
        
         for(int i=0; i<size; ++i)
         {
                catchError(stageResult: 'FAILURE')
            {
                stan = ' -stan 134'
                authCode = ' -auth 123456'
                log = ' -lp refundLog' + i.toString() + '.LOG'
                dir = ' -dir ../AutomationTesting/Tests/Sale_refund_wrong_input'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/refundError.txt ' + log + dir + stan + authCode
                bat str
            }
        }
    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            dir = ' -dir ../AutomationTesting/Tests/Sale_refund_wrong_input'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + log + dir
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 0)
            }
        }

        stage('sale')
        {
            steps
            {
                sale(1)
            }
            
        }

        stage('refund')
        {
            steps
            {
                refund(1)
            }
            
        }
        
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }
    }
}
