dir = ' -dir ../AutomationTesting/Tests/401_sales'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale(size, offset)
{
    script
    {
        for(int i= offset; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 39
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                log = ' -lp saleLog' + i.toString() + '.LOG'
                data = ' -out Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/sale0.txt ' + amount + dir + log + data
                bat str 
            }
        }
    }
}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {
        stage('Init')
        {
            steps
            {
                init() 
            }
        }

        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }

        stage('sale1')
        {
            steps
            {
                sale(50,0)
            }
            
        }
  
        stage('sale2')
        {
            steps
            {
                sale(100,50)
            }
            
        }
        stage('sale3')
        {
            steps
            {
                sale(150,100)
            }
            
        }
        stage('sale4')
        {
            steps
            {
                sale(200,150)
            }
            
        }
        stage('sale5')
        {
            steps
            {
                sale(250,200)
            }
            
        }
        stage('sale6')
        {
            steps
            {
                sale(300,250)
            }
            
        }
            
        stage('sale7')
        {
            steps
            {
                sale(350,300)
            }
            
        }
        stage('sale8')
        {
            steps
            {
                sale(400,350)
            }
            
        }       
        stage('sale9')
        {
            steps
            {
                sale(405,400)
            }
            
        } 
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
