dir = ' -dir ../AutomationTesting/Tests/401_sales'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale(size, offset)
{
    script
    {
        for(int i= offset; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 500
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                deviceID = ' -q 1234567890'
                trxID = ' -o 12345678901234'  
                log = ' -lp saleLog' + i.toString() + '.LOG'
                data = ' -out saleData' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/sale0.txt ' + amount + dir + log + data + deviceID + trxID
                bat str 
                
                /* log = ' -lp completeSaleLog' + i.toString() + '.LOG'
                data = ' -out completeSaleData' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/complete_sale.txt ' + dir + log + data
                bat str */
            }
        }
    }
}

 def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
} 

pipeline {
    agent any

    stages 
    {
        stage('Init')
        {
            steps
            {
                init() 
            }
        }

       /* stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }
*/
        stage('sale1')
        {
            steps
            {
                sale(1,0)
            }
            
        }
  
      /*   stage('sale2')
        {
            steps
            {
                sale(100,50)
            }
            
        }
        stage('sale3')
        {
            steps
            {
                sale(150,100)
            }
            
        }
        stage('sale4')
        {
            steps
            {
                sale(200,150)
            }
            
        }
        stage('sale5')
        {
            steps
            {
                sale(250,200)
            }
            
        }
        stage('sale6')
        {
            steps
            {
                sale(296,250)
            }
            
        }
*/
    }
}
