dir = ' -dir ../AutomationTesting/Tests/205_Preauth_PreauthComp_loop'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def preauth_preauthComp(size, offset)
{
        script
        {
            for(int i=offset;i<size;++i)
            {
                    max = 1
                    random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                    amount = '-a' + random_num.toString()
                    
                    log = ' -lp preauthLog' + i.toString() + '.LOG'
                    data = ' -out Data' + i.toString()+ '.txt'
                    
                    str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data
                    
                    catchError(stageResult: 'FAILURE')
                    {
                       bat str 
                    }
                

                    log = ' -lp preauthCompletionLog' + i.toString() + '.LOG'
                    data = ' -in Data' + i.toString()+ '.txt'
                    str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + dir + log + data
                    catchError(stageResult: 'FAILURE')
                    {
                         bat str
                    }
            }
        }
}


def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
            
        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 0)
            }
        }

        stage('preauths/preauthCompletions1')
        {
            steps
            {
                preauth_preauthComp(10, 0)
            }
            
        }
       
       /* stage('preauths/preauthCompletions2')
        {
            steps
            {
                preauth_preauthComp(100, 50)
            }
            
        }
        stage('preauths/preauthCompletions3')
        {
            steps
            {
                preauth_preauthComp(150, 100)
            }
            
        }    
        
        stage('preauths/preauthCompletions4')
        {
            steps
            {
                preauth_preauthComp(200, 150)
            }
            
        }
        stage('preauths/preauthCompletions5')
        {
            steps
            {
                preauth_preauthComp(201, 200)
            }
        } */
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }
    }
}
