
ip = ' -ip 192.168.1.2'
connType = '-t 0'
dir = ' -dir ../AutomationTesting/Tests/200_Preauth_PreauthComp_loop'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def preauth_preauthComp(size, offset)
{
        script
        {
            for(int i=offset;i<size;++i)
            {
                catchError(stageResult: 'FAILURE')
                {
                    max = 98
                    random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                    amount = '-a' + random_num.toString()
                    
                    log = ' -lp preauthLog' + i.toString() + '.LOG'
                    data = ' -out Data' + i.toString()+ '.txt'
                    
                    str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + dir + log + data
                    bat str 


                    log = ' -lp preauthCompletionLog' + i.toString() + '.LOG'
                    data = ' -in Data' + i.toString()+ '.txt'
                    str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + dir + log + data
                    bat str
                }
            }
            
        }
}


def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
            
        stage('closeBatch1')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 0)
            }
        }

        stage('preauths/preauthCompletions1')
        {
            steps
            {
                preauth_preauthComp(100, 0)
            }
            
        }
        stage('preauths/preauthCompletions2')
        {
            steps
            {
                preauth_preauthComp(200, 100)
            }
            
        }
        stage('preauths/preauthCompletions2')
        {
            steps
            {
                preauth_preauthComp(205, 200)
            }
            
        }

        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 1)
            }
        }
    }
}
