dir = ' -dir ../AutomationTesting/Tests/sales_then_refunds'

def init()
{
        script
        {
                bat 'python.exe ../AutomationTesting/SetupTest.py '
        }
}

def sale(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 22
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                log = ' -lp saleLog' + i.toString() + '.LOG'
                data = ' -out Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/sale0.txt ' + amount + data + dir + log
                bat str 
            }
        }
    }
}
def refund(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                log = ' -lp refundLog' + i.toString() + '.LOG'
                data = ' -in Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/refund0.txt ' + data + dir + log
                bat str
            }
        }

    }

}

def closeBatch(valPath, index)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            log = ' -lp closeBatchLog' + index.toString() + '.LOG'
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath + dir + log
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {

        stage('Init')
        {
            steps
            {
                init() 
            }
        }
        stage('closeBatch1')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch1.txt', 1)
            }
        }

        stage('sales')
        {
            steps
            {
                sale(100)
            }
            
        }
        stage('sales2')
        {
            steps
            {
                sale(100)
            }
            
        }
             stage('sales3')
        {
            steps
            {
                sale(5)
            }
            
        }
        stage('refunds1')
        {
            steps
            {
                refund(100)
            }
            
        }
            stage('refunds')
        {
            steps
            {
                refund(100)
            }
            
        }
        stage('refunds')
        {
            steps
            {
                refund(5)
            }
            
        }
        stage('closeBatch2')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt', 2)
            }
        }
    }
}
