
ip = ' -ip 192.168.1.2'
connType = '-t 0'

def preauth(size, offset)
{
    script
    {
        for(int i= offset; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                data = ' -out ../AutomationTesting/transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauth0.txt ' + amount + data
                bat str 
            }
        }
    }
}

def preauthComp(size, offset)
{
    script
    {
        for(int i= offset; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                data = '-in ../AutomationTesting/transData/Data' + i.toString()+ '.txt'
                str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ../AutomationTesting/validation/preauthCompletion0.txt ' + data
                bat str
            }
        }
    }

}

def closeBatch(valPath)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            str = 'python.exe ../AutomationTesting/Main.py ' + connType + ip +' -vp ' + valPath
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('closeBatchStart')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }

        stage('preauth1')
        {
            steps
            {
                preauth(100,0)
            }
            
        }
        
        stage('preauth2')
        {
            steps
            {
                preauth(200,100)
            }
            
        }
        stage('preauthCompletion')
        {
            steps
            {
                preauthComp(1,0)
            }
        }
   
        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }
    }
}
