/* SALE REVERSAL REVERSAL */


dir = ' -dir ../AutomationTesting/Tests/sale_refund_refund'

def sale_reversalx2(size)
{
    script
    {
        for(int i=0; i<size; ++i)
        {
            catchError(stageResult: 'FAILURE')
            {
                max = 98
                random_num = "${Math.abs(1 + new Random().nextInt(max+1))}"
                amount = '-a' + random_num.toString()
                data = ' -out Data' + i.toString()+ '.txt'
                log = ' -lp saleLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/sale0.txt ' + amount + data + dir + log
                bat str

                data = ' -in Data' + i.toString()+ '.txt'
                log = ' -lp saleLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/reversal0.txt ' + data + dir + log
                bat str

                data = ' -in Data' + i.toString()+ '.txt'
                log = ' -lp saleLog' + i.toString() + '.LOG'
                str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ../AutomationTesting/validation/reversal0.txt ' + data + dir + log
                bat str 
            }
        }
    }
}

def closeBatch(valPath)
{
    script
    {
        catchError(stageResult: 'FAILURE')
        {
            str = 'python.exe ../AutomationTesting/Main.py ' + ' -vp ' + valPath
            bat str
        }
    }
}

pipeline {
    agent any

    stages 
    {


        stage('closeBatchStart')
        {
            steps
            {
                        
                closeBatch('../AutomationTesting/validation/closeBatch1.txt')
            }
        }

         stage('sale_reversal_reversal1')
        {
            steps
            {
                sale_reversalx2(33)
            }
            
        }
         stage('sale_reversal_reversal2')
        {
            steps
            {
                sale_reversalx2(33)
            }
            
        }
         stage('sale_reversal_reversal3')
        {
            steps
            {
                sale_reversalx2(33)
            }
            
        }
        
        stage('closeBatch')
        {
            steps
            {
                closeBatch('../AutomationTesting/validation/closeBatch.txt')
            }
        }
    }
}
